import type { Metadata } from "next";
import "./globals.css";
import { NotificationBanner } from "@/components/notifcation-banner";
import { FixedHeader } from "@/components/header";
import { LayoutSpacer } from "@/components/layout-sapcer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NotificationBanner message="Get 70% off Verzo premium for the first 3 months" />
        <FixedHeader />
        <LayoutSpacer />
        {children}
      </body>
    </html>
  );
}
