import type { Metadata } from "next";
import "./globals.css";
import { NotificationBanner } from "@/components/notifcation-banner";
import { NotificationProvider } from "@/components/notification-context";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NotificationProvider>
          <NotificationBanner message="Get 70% off Verzo premium for the first 3 months" />
          {children}
        </NotificationProvider>
      </body>
    </html>
  );
}
